SELECT F_NAME, L_NAME
FROM EMPLOYEES
WHERE ADDRESS LIKE '%Elgin,IL%';

SELECT F_NAME, L_NAME
FROM EMPLOYEES
WHERE B_DATE LIKE '197%';

SELECT *
FROM EMPLOYEES
WHERE (SALARY BETWEEN 60000 AND 70000) AND DEP_ID = 5;

SELECT F_NAME, L_NAME, DEP_ID 
FROM EMPLOYEES
ORDER BY DEP_ID;

SELECT F_NAME, L_NAME, DEP_ID 
FROM EMPLOYEES
ORDER BY DEP_ID DESC, L_NAME DESC;

SELECT DEP_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*), AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEP_ID
ORDER BY AVG_SALARY;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING count(*) < 4
ORDER BY AVG_SALARY;

SELECT * 
FROM EMPLOYEES 
WHERE 
	EMPLOYEES.F_NAME LIKE 'S%' 
	OR EMPLOYEES.L_NAME LIKE 'S%';

SELECT * 
FROM EMPLOYEES 
ORDER BY EMPLOYEES.B_DATE ASC;

SELECT 
	EMPLOYEES.DEP_ID,
    AVG(EMPLOYEES.SALARY) AS AVG_SALARY 
FROM EMPLOYEES 
GROUP BY DEP_ID 
HAVING AVG_SALARY >= 60000;

SELECT 
	EMPLOYEES.DEP_ID,
	AVG(EMPLOYEES.SALARY) AS AVG_SALARY 
FROM EMPLOYEES 
GROUP BY DEP_ID 
HAVING AVG_SALARY >= 60000 
ORDER BY AVG_SALARY DESC;